# Base build settings for Netlify
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  # Ensures devDependencies (like Playwright) are installed for testing commands
  NPM_FLAGS = "--production=false"

# Netlify Forms configuration
[forms]
  # Enables automatic form detection for forms named "contact" and "newsletter"
  contact = true
  newsletter = true

# Global security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security: Prevents the site from being rendered in an iframe
    X-Frame-Options = "DENY"
    # Security: Enables browser's built-in XSS protection
    X-XSS-Protection = "1; mode=block"
    # Security: Prevents MIME-sniffing attacks
    X-Content-Type-Options = "nosniff"
    # Security: Controls how much referrer information is sent
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Security: Specifies which browser features the site can use
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Security: Content Security Policy to prevent XSS and data injection attacks
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https://res.cloudinary.com;
      media-src 'self' https://res.cloudinary.com;
      connect-src 'self' https://vitals.vercel-analytics.com;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

# Caching rules for immutable static assets (one year)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Caching rules for other assets like fonts, images not in /assets
[[headers]]
  for = "/(images|fonts)/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Caching rules for HTML pages (do not cache long, revalidate often)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Service worker file must be revalidated every time
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

# Prevent the admin area from being indexed by search engines
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"

# SEO and User Experience Redirects
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/work"
  to = "/portfolio"
  status = 301

# Netlify CMS admin panel rewrite
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# 404 fallback page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Netlify Plugins for Astro
[[plugins]]
  # Generates a sitemap.xml for your site
  package = "@netlify/plugin-sitemap"

[[plugins]]
  # Runs Lighthouse performance audits on deploys
  package = "netlify-plugin-lighthouse"
  [plugins.inputs]
    # You can set performance budgets here if desired
    # See plugin docs for more options
    output_path = "reports/lighthouse.html"

# Production context
[context.production]
  [context.production.environment]
    NODE_ENV = "production"

# Deploy Preview context
[context.deploy-preview]
  command = "npm run build" # Or a specific preview build command if you have one

# Netlify Dev server configuration
[dev]
  command = "npm run dev"
  port = 8888
  publish = "dist"
  autoLaunch = true