# This backend is for local development. It uses the file system and requires no login.
backend:
  name: test-repo

# When you deploy to Netlify, you will comment out the 'test-repo' backend
# and uncomment the 'git-gateway' backend below.
# backend:
#   name: git-gateway
#   branch: main

# Where to store uploaded images. Cloudinary is the primary.
media_library:
  name: cloudinary
  config:
    cloud_name: "YOUR_CLOUD_NAME_HERE" # IMPORTANT: Replace with your Cloudinary cloud name
    api_key: "685338551245488"
media_folder: "src/assets/images/uploads" # Fallback storage location
public_folder: "/assets/images/uploads"

# The 'collections' property is required and must be a list (indicated by the '-')
collections:
  # Collection for the single home page
  - name: "home"
    label: "Home Page"
    files:
      - label: "Home Page Content"
        name: "home"
        file: "src/content/home/home.md" # Note the correct path
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }

  # Collection for portfolio projects
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover_image", widget: "image" }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt Text", name: "alt", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }

  # Collection for blog posts
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
